# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-13 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegoSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lego_id', models.IntegerField(default=0)),
                ('set_name', models.CharField(default='placeholder_name', max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estimated_selling_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actual_selling_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
