# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-14 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
