# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-13 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('owner', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actual_selling_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='legoset',
            name='actual_selling_price',
        ),
        migrations.RemoveField(
            model_name='legoset',
            name='id',
        ),
        migrations.RemoveField(
            model_name='legoset',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='legoset',
            name='shipping_cost',
        ),
        migrations.AlterField(
            model_name='legoset',
            name='lego_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='lego_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.LegoSet'),
        ),
    ]
