# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-13 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20191013_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legoset',
            name='lego_id',
            field=models.CharField(default='0', max_length=20, primary_key=True, serialize=False),
        ),
    ]
