# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-25 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_legoset_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
