# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-26 18:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_collectionitem_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='date_purchased',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
