# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-29 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_collectionitem_date_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='raffle',
            field=models.BooleanField(default=False),
        ),
    ]
